# Generated by Django 3.0.2 on 2020-01-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200131_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qqusers',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
