# Generated by Django 3.0.2 on 2020-02-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200131_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='qqusers',
            name='user_icon',
            field=models.ImageField(default='default_img/user_icon.png', help_text='QQ头像', upload_to='icons', verbose_name='用户头像'),
        ),
    ]
